# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://db.zclxrrjkcteilzlzlqhq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=c1rmee94!SPESE
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection pool configuration (optional, uses HikariCP by default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.base-url=/api/v1

# Controller base path
server.servlet.context-path=/api/v1